### PR TITLE
Added basic classes we'll need

### PR DESCRIPTION
**Pull request by markd315**
Not fully commented or tested

### CODE REVIEW

**Comment by f0lie** [comment]
We shouldn't add classes just yet. We need to define the scope of the project and recognize what needs to be worked on first before we begin anything. If we add classes now, we would be tunneled visioned into constructing everything around that.

I am not saying we are going with waterfall. I am saying we need a bigger picture to put the classes in perspective and they we can learn more from their implementation.

**Comment by markd315** [comment]
Did more basic stuff and changed the underscoring on var names.

**Comment by markd315** [comment]
I've done a lot of work at this point.  Feel free to change around any implementations you don't like, but this should pretty much be the shell we want to start from.  We now need to work on graphical representations and getting the objects to interact in space.  Someone make map/tile classes?

**Comment by f0lie** [comment]
Why is there implementation in the header files?
Enemy.hpp is an large file with a lot of cross domain code and thats not even a cpp file. Lets try to get a entity drawn on the screen so we can know what to add and what not to add.

I realized that thinking about component design is too far ahead.

**Comment by f0lie** [comment]
http://gameprogrammingpatterns.com/component.html

**Comment by markd315** [comment]
I do my class implementation (everything but main loops etc) in the header files.  Fewer files, don't have to do the Player::Player(args) thing that annoys me.  Disadvantage is that you have to order it.  If you want for this project I will conform to the typical norms, I can fix it like that later or do it yourself.

**Pull request merged**
